#!/bin/bash -e
apt-get update -y
apt-get install samba -y
mkdir /srv/kozos
chmod 777 /srv/kozos
mv /etc/samba/smb.conf /etc/samba/smbold.conf
cp smb.conf /etc/samba/smb.conf
service smbd restart
adduser user2 --gecos "user2,,," --disabled-password
echo "user2:diak" | chpasswd
mkdir /srv/user2
chown user2 /srv/user2
chmod 700 /srv/user2
echo "Adja meg a(z) user2 felhasználó smb jelszavát: "
smbpasswd -a user2
service smbd restart
