#!/bin/bash -e
apt-get update -y
apt-get install tasksel mc zip -y
tasksel install lamp-server
mysql -h "lamp-server" -u root "123" "wordpressdb" < "exec.sql"
CREATE DATABASE wordpressdb;
CREATE USER wordpressuser@localhost IDENTIFIED BY 'wordpresspassword';
GRANT ALL PRIVILEGES ON wordpressdb.* TO wordpressuser@localhost;
FLUSH PRIVILEGES;
exit
cd /tmp
wget http://wordpress.org/latest.zip
unzip -q latest.zip -d /var/www/html/
chown -R www-data:www-data /var/www/html/wordpress
chmod -R 755 /var/www/html/wordpress
mkdir -p /var/www/html/wordpress/wp-content/uploads
chown -R www-data:www-data /var/www/html/wordpress/wp-content/uploads 
service apache2 restart
apt-get install php7.0-mysql
